<h2>Welcome to Mageplaza.com</h2>
<div>
    <p>
        Lorem ipsum dolor sit amet, consectetur adipisicing elit. Animi asperiores beatae consectetur doloribus et illum in, ipsum iure laudantium nobis obcaecati placeat saepe sapiente? Error itaque numquam quas ratione voluptates?
    </p>
</div>

<div class="email">
    <p>Email</p>
    <input class="validation" type="email" ame="login[username]" value="" autocomplete="off" id="email" title="Email" data-validate="{required:true, 'validate-email':true}" aria-required="true">
    <button class="action subscribe primary" title="Subscribe" type="submit" aria-label="Subscribe" ma>send</button>
</div>
<div class="result">

</div>
<style>
    .email{
        width: 30%;
    }
    .email button{
        margin-top: 4%;
    }
</style>
